### ISSUE TITLE
Timecode Length Improper Display

### ISSUE THREAD

**Issue by Nate463** [cybertron-cube/CyberVideoPlayer#30]
**Describe the bug**
When opening a media file, timecode length shrinks from desired output to a more condensed version. In the settings.json file, "TimeCodeLength": 12 is being used and works when just opening the program, but changes when opening a file.

**To Reproduce**
1. Open CyberVideoPlayer
2. Drag and Drop video on player, or use 'File' and 'Open'

**Expected behavior**
Timecode Length respects parameter set in settings.json

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Version 22631.3447 (23H2)

**Comment by cybertron-cube** [comment]
I am not able to reproduce this however I suspect your issue is that you have the time code length set in the settings.json file that is adjacent to the executable. The location that the application reads settings and writes logs to has [changed](https://github.com/cybertron-cube/CyberVideoPlayer/commit/56b6f878dadb07466fe81615ff4c2f0fb0f0455b#diff-fee277303b129c049fd5691ef76a26ecb7562a6dcad29ffbdd6c535ffba1f9e6R29) and is now located in %appdata%\CyberVideoPlayer on windows.
